workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 15
    environment:
      flutter: "3.22.1"  # <-- Versão estável mais recente (maio/2025)
    scripts:
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
